/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package com.guisehn.telas;

import com.guisehn.db.TemasProvider;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author guilhermesehn
 */
public class TelaListagemTemas extends javax.swing.JFrame {

    private final DefaultTableModel model;
    private final TelaAdicionarTema telaAdicionarTema;
    private TelaPrincipal telaPrincipal;
    private List<String> temas;
    
    /**
     * Creates new form TelaCadastroTemas
     */
    public TelaListagemTemas() {
        this.temas = new ArrayList<>();
        initComponents();
        
        telaAdicionarTema = new TelaAdicionarTema();
        telaAdicionarTema.setTelaListagemTemas(this);
        
        model = new DefaultTableModel(
            new Object[][] {},
            new Object[] { "Tema" }
        ) {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            } 
        };
        
        tblTemas.setModel(model);
    }

    public void atualizar() {
        // Remove todas as linhas
        int numRows = model.getRowCount();
        for (int i = numRows - 1; i >= 0; i--) {
            model.removeRow(i);
        }
        
        // Escreve de novo
        temas = TemasProvider.buscarTemas();
        for (String tema : temas) {
            model.addRow(new Object[] {
                tema
            });
        }
        
        // Atualiza temas da tela principal
        if (telaPrincipal != null)
            telaPrincipal.atualizarTemas();
    }

    public void setTelaPrincipal(TelaPrincipal telaPrincipal) {
        this.telaPrincipal = telaPrincipal;
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT
     * modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnAdicionarTema = new javax.swing.JButton();
        btnExcluirTema = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblTemas = new javax.swing.JTable();

        setTitle("Cadastro de temas");

        btnAdicionarTema.setText("Adicionar tema");
        btnAdicionarTema.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdicionarTemaActionPerformed(evt);
            }
        });

        btnExcluirTema.setText("Excluir tema");
        btnExcluirTema.setToolTipText("");
        btnExcluirTema.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirTemaActionPerformed(evt);
            }
        });

        tblTemas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblTemas.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane1.setViewportView(tblTemas);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnAdicionarTema)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 127, Short.MAX_VALUE)
                        .addComponent(btnExcluirTema))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAdicionarTema)
                    .addComponent(btnExcluirTema))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 275, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAdicionarTemaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdicionarTemaActionPerformed
        telaAdicionarTema.setVisible(true);
        telaAdicionarTema.limparCampo();
        telaAdicionarTema.focarCampo();
    }//GEN-LAST:event_btnAdicionarTemaActionPerformed

    private void btnExcluirTemaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirTemaActionPerformed
        int row = tblTemas.getSelectedRow();
        
        if (row == -1) {
            JOptionPane.showMessageDialog(null, "Selecione um tema");
            return;
        }
        
        String tema = temas.get(row);
        
        int opcao = JOptionPane.showConfirmDialog(
            null,
            "Deseja mesmo excluir o tema \"" + tema + "\"? Todas as palavras associadas a ele serão excluidas.",
            "Excluir tema",
            JOptionPane.YES_NO_OPTION
        );
        
        if (opcao == JOptionPane.YES_OPTION) {
            TemasProvider.excluirTema(tema);
            atualizar();
        }
    }//GEN-LAST:event_btnExcluirTemaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaListagemTemas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaListagemTemas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaListagemTemas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaListagemTemas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaListagemTemas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdicionarTema;
    private javax.swing.JButton btnExcluirTema;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblTemas;
    // End of variables declaration//GEN-END:variables
}
